blank_issues_enabled: false
contact_links:
  - name: Bug reports & feature requests
    url: https://github.com/spairehq/spaire/issues/new/choose
    about: Please open all issues in our main issue tracker.
